---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: test-work
  name: nginx
  namespace: wego-system
spec:
  path: ./
  url: ssh://git@github.com/J-Thompson12/nginx.git
