---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  name: nginx1
  labels:
    name: wego-568e6e88c7fb543690f63de356136305
spec:
  path: ./
  url: ssh://git@github.com/J-Thompson12/nginx.git
