---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: testPR
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./new
  prune: true
  sourceRef:
    kind: GitRepository
    name: testPR
  validation: client

