---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx2
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/J-Thompson12/nginx.git

